plugins:
  wikimedia_auth_enabled: true
  wikimedia_consumer_key: ""
  wikimedia_consumer_secret: ""
  wikimedia_callback_url: "oob"
  wikimedia_auth_site: "https://meta.wikimedia.org"
  wikimedia_username_conformity_login: false